name: Build
on:
  push:
    branches: [master, branch-*, dogfood-*]
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: github-ubuntu-latest-m
    steps:
      - &checkout
        name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - &mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          deploy-pull-request: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          sonar-platform: next
          maven-args: '-T1C'

  build-windows:
    needs: [build]
    runs-on: windows-latest
    steps:
      - *checkout
      - *mise
      - name: Build Maven (no deploy)
        uses: SonarSource/ci-github-actions/build-maven@master
        with:
          deploy: false
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          sonar-platform: none
          maven-args: '-T1C'

  qa:
    if: github.actor != 'dependabot[bot]'
    needs: [build]
    runs-on: github-ubuntu-latest-m
    strategy:
      matrix:
        sq-version: [LATEST_RELEASE, DEV]
    permissions:
      id-token: write
      contents: read
    steps:
      - *checkout
      - *mise
      - &config_maven
        uses: SonarSource/ci-github-actions/config-maven@v1
        with:
          artifactory-reader-role: private-reader
      - &secrets
        name: Vault
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/github/token/licenses-ro token | GITHUB_TOKEN_LICENSES;
            development/kv/data/repox url | ARTIFACTORY_URL;
            development/artifactory/token/SonarSource-sonar-html-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;
      - name: Run QA tests
        env: &qa_env
          SONARSOURCE_QA: true
          GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault)['GITHUB_TOKEN_LICENSES'] }}
          ARTIFACTORY_URL: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_URL }}
          ARTIFACTORY_ACCESS_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).ARTIFACTORY_ACCESS_TOKEN }}
        run: |
          mvn -f its/plugin/pom.xml verify -Pqa -Dsonar.runtimeVersion=${{ matrix.sq-version }} -Dmaven.test.redirectTestOutputToFile=false -B -e -V

  ruling:
    if: github.actor != 'dependabot[bot]'
    needs: [build]
    runs-on: github-ubuntu-latest-m
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true
      - *mise
      - *config_maven
      - *secrets
      - name: Run ruling tests
        env: *qa_env
        run: |
          mvn -f its/ruling/pom.xml verify -Pqa -Dsonar.runtimeVersion=LATEST_RELEASE -Dmaven.test.redirectTestOutputToFile=false -B -e -V
      - name: Show ruling differences
        if: failure()
        run: ./tools/ruling-debug-script.sh

  promote:
    needs: [build, build-windows, qa, ruling]
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - *checkout
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          version: 2025.7.12
          cache_save: false
      - uses: SonarSource/ci-github-actions/promote@v1
        with:
          promote-pull-request: true
