name: Nightly
on:
  schedule:
    - cron: '0 2 * * *'  # Run nightly at 2 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  analyze:
    runs-on: github-ubuntu-latest-s
    strategy:
      matrix:
        include:
          - platform: next
            project-key: org.sonarsource.html:html
          - platform: sqc-eu
            project-key: SonarSource_sonar-html
          - platform: sqc-us
            project-key: SonarSource_sonar-html
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          maven-args: "-Dsonar.projectKey=${{ matrix.project-key }} -Dsonar.organization=sonarsource -Pcoverage-report -Dmaven.install.skip=true -Dmaven.deploy.skip=true"
          sonar-platform: ${{ matrix.platform }}

  iris:
    needs: [analyze]
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
        with:
          version: 2025.7.12
      - uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: org.sonarsource.html:html
          primary_platform: Next
          shadow1_project_key: SonarSource_sonar-html
          shadow1_platform: SQC-EU
          shadow2_project_key: SonarSource_sonar-html
          shadow2_platform: SQC-US
